%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\artur\Downloads\Data_for_test.xlsx
%    Worksheet: Feuil1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2020/02/24 14:36:22

%% Import the data
function C = SourisXLS(filename)
[NUM,TXT,~]= xlsread(filename);
[NoOfRows,NoOfColumn]= size(NUM);

for i = 1:NoOfColumn
    TXT{1,i}=TXT{1,i}(1:3); %Keep the label of each cell recording
end
C={TXT;NUM};
